//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        public int ID_ACTIVIDAD { get; set; }
        public string NOMBREACTIVIDAD { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual PROGRAMAS PROGRAMAS { get; set; }
    }
}
