//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUMNOS()
        {
            this.INTERCAMBIO = new HashSet<INTERCAMBIO>();
            this.NOTAS = new HashSet<NOTAS>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int ID_ALUMNO { get; set; }
        public string DV { get; set; }
        public string NOMBRE { get; set; }
        public string APELL_PATERNO { get; set; }
        public string APELL_MATERNO { get; set; }
        public string CORREO { get; set; }
        public Nullable<int> RESERVA { get; set; }
        public long TELEFONO { get; set; }
        public string ESTADO_MORA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERCAMBIO> INTERCAMBIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS> NOTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
