//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVOFAMILIA
    {
        public int ID_ARCHIVO_FAMILIA { get; set; }
        public string DIRECCION_ENLACE { get; set; }
        public string TIPO_ARCHIVO { get; set; }
        public int ID_FAMILIA { get; set; }
    
        public virtual FAMILIASANFITRIONA FAMILIASANFITRIONA { get; set; }
    }
}
