//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUCION
    {
        public int ID_INSTITUCION { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public Nullable<long> TELEFONO { get; set; }
        public string PAGINA_WEB { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> ID_CIUDAD { get; set; }
        public Nullable<int> ID_PAIS { get; set; }
    }
}
