//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTITUCION()
        {
            this.ENCARGADO_CEL = new HashSet<ENCARGADO_CEL>();
            this.PROGRAMAS = new HashSet<PROGRAMAS>();
        }
    
        public int ID_INSTITUCION { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public Nullable<long> TELEFONO { get; set; }
        public string PAGINA_WEB { get; set; }
        public string DIRECCION { get; set; }
        public int ID_CIUDAD { get; set; }
        public int ID_PAIS { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCARGADO_CEL> ENCARGADO_CEL { get; set; }
        public virtual PAIS PAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRAMAS> PROGRAMAS { get; set; }
    }
}
