//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERCAMBIO
    {
        public int ID_INTERCAMBIO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> ID_ADMINISTRATIVO { get; set; }
        public Nullable<int> ID_FAMILIA { get; set; }
        public Nullable<int> ID_ALUMNO { get; set; }
        public Nullable<int> ID_PROGRAMA { get; set; }
    
        public virtual ADMINISTRATIVO ADMINISTRATIVO { get; set; }
        public virtual ALUMNOS ALUMNOS { get; set; }
        public virtual FAMILIASANFITRIONA FAMILIASANFITRIONA { get; set; }
        public virtual PROGRAMAS PROGRAMAS { get; set; }
    }
}
