//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMAS
    {
        public int ID_PROGRAMA { get; set; }
        public string NOMBRE_PROGRAMA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CUPOS { get; set; }
        public int ID_INSTITUCION { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public string TIPO_CURSO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual INSTITUCION INSTITUCION { get; set; }
    }
}
