//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NOTAS_ALUMNO
    {
        public string Nombre { get; set; }
        public string NOMBRE_PROGRAMA { get; set; }
        public Nullable<decimal> NOTA { get; set; }
    }
}
