//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PROGRAMAS_POSTULADOS
    {
        public int ID_PROGRAMA { get; set; }
        public string NOMBRE_PROGRAMA { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public string Encargado_Cel { get; set; }
        public string Institucion { get; set; }
        public string NOM_PAIS { get; set; }
        public string NOM_CIUDAD { get; set; }
    }
}
