//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC.Portafolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_DETALLE_POSTULACION
    {
        public string NOMBRE_POSTULANTE { get; set; }
        public int ID_ALUMNO { get; set; }
        public string CORREO_POSTULANTE { get; set; }
        public long TELEFONO_POSTULANTE { get; set; }
        public string ESTADO_MORA { get; set; }
        public string NOMBRE_FAMILIA_ANFITRIONA { get; set; }
        public int ID_FAMILIA { get; set; }
        public string DIRECCION_FAMILIA { get; set; }
        public string CORREO_FAMILIA { get; set; }
        public long TELEFONO_FAMILIA { get; set; }
        public int ID_PROGRAMA { get; set; }
        public string NOMBRE_PROGRAMA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CUPOS { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public string TIPO_CURSO { get; set; }
        public string CIUDAD_FAMILIA { get; set; }
        public string NOMBRE_PAIS { get; set; }
        public string NOMBRE_INSTITUCION { get; set; }
        public int ID_INTERCAMBIO { get; set; }
    }
}
