//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Portafolio.Servicios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicios.IServicios")]
    public interface IServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosPaises", ReplyAction="http://tempuri.org/IServicios/LeerTodosPaisesResponse")]
        string LeerTodosPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosPaises", ReplyAction="http://tempuri.org/IServicios/LeerTodosPaisesResponse")]
        System.Threading.Tasks.Task<string> LeerTodosPaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearPrograma", ReplyAction="http://tempuri.org/IServicios/CrearProgramaResponse")]
        bool CrearPrograma(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearPrograma", ReplyAction="http://tempuri.org/IServicios/CrearProgramaResponse")]
        System.Threading.Tasks.Task<bool> CrearProgramaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerPrograma", ReplyAction="http://tempuri.org/IServicios/LeerProgramaResponse")]
        string LeerPrograma(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerPrograma", ReplyAction="http://tempuri.org/IServicios/LeerProgramaResponse")]
        System.Threading.Tasks.Task<string> LeerProgramaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarPrograma", ReplyAction="http://tempuri.org/IServicios/ActualizarProgramaResponse")]
        bool ActualizarPrograma(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarPrograma", ReplyAction="http://tempuri.org/IServicios/ActualizarProgramaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProgramaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarPrograma", ReplyAction="http://tempuri.org/IServicios/EliminarProgramaResponse")]
        bool EliminarPrograma(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarPrograma", ReplyAction="http://tempuri.org/IServicios/EliminarProgramaResponse")]
        System.Threading.Tasks.Task<bool> EliminarProgramaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosProgramas", ReplyAction="http://tempuri.org/IServicios/LeerTodosProgramasResponse")]
        string LeerTodosProgramas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosProgramas", ReplyAction="http://tempuri.org/IServicios/LeerTodosProgramasResponse")]
        System.Threading.Tasks.Task<string> LeerTodosProgramasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/validarUsuario", ReplyAction="http://tempuri.org/IServicios/validarUsuarioResponse")]
        bool validarUsuario(string userPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/validarUsuario", ReplyAction="http://tempuri.org/IServicios/validarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> validarUsuarioAsync(string userPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearUsuario", ReplyAction="http://tempuri.org/IServicios/CrearUsuarioResponse")]
        bool CrearUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearUsuario", ReplyAction="http://tempuri.org/IServicios/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerUsuario", ReplyAction="http://tempuri.org/IServicios/LeerUsuarioResponse")]
        string LeerUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerUsuario", ReplyAction="http://tempuri.org/IServicios/LeerUsuarioResponse")]
        System.Threading.Tasks.Task<string> LeerUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarUsuario", ReplyAction="http://tempuri.org/IServicios/ActualizarUsuarioResponse")]
        bool ActualizarUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarUsuario", ReplyAction="http://tempuri.org/IServicios/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarUsuario", ReplyAction="http://tempuri.org/IServicios/EliminarUsuarioResponse")]
        bool EliminarUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarUsuario", ReplyAction="http://tempuri.org/IServicios/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosUsuarios", ReplyAction="http://tempuri.org/IServicios/LeerTodosUsuariosResponse")]
        string LeerTodosUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosUsuarios", ReplyAction="http://tempuri.org/IServicios/LeerTodosUsuariosResponse")]
        System.Threading.Tasks.Task<string> LeerTodosUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ReadAllVNotasPrograma", ReplyAction="http://tempuri.org/IServicios/ReadAllVNotasProgramaResponse")]
        string ReadAllVNotasPrograma(int idALumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ReadAllVNotasPrograma", ReplyAction="http://tempuri.org/IServicios/ReadAllVNotasProgramaResponse")]
        System.Threading.Tasks.Task<string> ReadAllVNotasProgramaAsync(int idALumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearActividad", ReplyAction="http://tempuri.org/IServicios/CrearActividadResponse")]
        bool CrearActividad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearActividad", ReplyAction="http://tempuri.org/IServicios/CrearActividadResponse")]
        System.Threading.Tasks.Task<bool> CrearActividadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerActividad", ReplyAction="http://tempuri.org/IServicios/LeerActividadResponse")]
        string LeerActividad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerActividad", ReplyAction="http://tempuri.org/IServicios/LeerActividadResponse")]
        System.Threading.Tasks.Task<string> LeerActividadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarActividad", ReplyAction="http://tempuri.org/IServicios/ActualizarActividadResponse")]
        bool ActualizarActividad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarActividad", ReplyAction="http://tempuri.org/IServicios/ActualizarActividadResponse")]
        System.Threading.Tasks.Task<bool> ActualizarActividadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarActividad", ReplyAction="http://tempuri.org/IServicios/EliminarActividadResponse")]
        bool EliminarActividad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarActividad", ReplyAction="http://tempuri.org/IServicios/EliminarActividadResponse")]
        System.Threading.Tasks.Task<bool> EliminarActividadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasActividades", ReplyAction="http://tempuri.org/IServicios/LeerTodasActividadesResponse")]
        string LeerTodasActividades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasActividades", ReplyAction="http://tempuri.org/IServicios/LeerTodasActividadesResponse")]
        System.Threading.Tasks.Task<string> LeerTodasActividadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EnlazarPrograma", ReplyAction="http://tempuri.org/IServicios/EnlazarProgramaResponse")]
        bool EnlazarPrograma(int idPrograma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EnlazarPrograma", ReplyAction="http://tempuri.org/IServicios/EnlazarProgramaResponse")]
        System.Threading.Tasks.Task<bool> EnlazarProgramaAsync(int idPrograma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/DesenlazarPrograma", ReplyAction="http://tempuri.org/IServicios/DesenlazarProgramaResponse")]
        bool DesenlazarPrograma();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/DesenlazarPrograma", ReplyAction="http://tempuri.org/IServicios/DesenlazarProgramaResponse")]
        System.Threading.Tasks.Task<bool> DesenlazarProgramaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearAdministrativo", ReplyAction="http://tempuri.org/IServicios/CrearAdministrativoResponse")]
        bool CrearAdministrativo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearAdministrativo", ReplyAction="http://tempuri.org/IServicios/CrearAdministrativoResponse")]
        System.Threading.Tasks.Task<bool> CrearAdministrativoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerAdministrativo", ReplyAction="http://tempuri.org/IServicios/LeerAdministrativoResponse")]
        string LeerAdministrativo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerAdministrativo", ReplyAction="http://tempuri.org/IServicios/LeerAdministrativoResponse")]
        System.Threading.Tasks.Task<string> LeerAdministrativoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarAdministrativo", ReplyAction="http://tempuri.org/IServicios/ActualizarAdministrativoResponse")]
        bool ActualizarAdministrativo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarAdministrativo", ReplyAction="http://tempuri.org/IServicios/ActualizarAdministrativoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAdministrativoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarAdministrativo", ReplyAction="http://tempuri.org/IServicios/EliminarAdministrativoResponse")]
        bool EliminarAdministrativo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarAdministrativo", ReplyAction="http://tempuri.org/IServicios/EliminarAdministrativoResponse")]
        System.Threading.Tasks.Task<bool> EliminarAdministrativoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosAdministrativos", ReplyAction="http://tempuri.org/IServicios/LeerTodosAdministrativosResponse")]
        string LeerTodosAdministrativos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosAdministrativos", ReplyAction="http://tempuri.org/IServicios/LeerTodosAdministrativosResponse")]
        System.Threading.Tasks.Task<string> LeerTodosAdministrativosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearAlumno", ReplyAction="http://tempuri.org/IServicios/CrearAlumnoResponse")]
        bool CrearAlumno(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearAlumno", ReplyAction="http://tempuri.org/IServicios/CrearAlumnoResponse")]
        System.Threading.Tasks.Task<bool> CrearAlumnoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerAlumno", ReplyAction="http://tempuri.org/IServicios/LeerAlumnoResponse")]
        string LeerAlumno(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerAlumno", ReplyAction="http://tempuri.org/IServicios/LeerAlumnoResponse")]
        System.Threading.Tasks.Task<string> LeerAlumnoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarAlumno", ReplyAction="http://tempuri.org/IServicios/ActualizarAlumnoResponse")]
        bool ActualizarAlumno(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarAlumno", ReplyAction="http://tempuri.org/IServicios/ActualizarAlumnoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAlumnoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarAlumno", ReplyAction="http://tempuri.org/IServicios/EliminarAlumnoResponse")]
        bool EliminarAlumno(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarAlumno", ReplyAction="http://tempuri.org/IServicios/EliminarAlumnoResponse")]
        System.Threading.Tasks.Task<bool> EliminarAlumnoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosAlumnos", ReplyAction="http://tempuri.org/IServicios/LeerTodosAlumnosResponse")]
        string LeerTodosAlumnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosAlumnos", ReplyAction="http://tempuri.org/IServicios/LeerTodosAlumnosResponse")]
        System.Threading.Tasks.Task<string> LeerTodosAlumnosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BuscarALumnosPorNombreCompleto", ReplyAction="http://tempuri.org/IServicios/BuscarALumnosPorNombreCompletoResponse")]
        string BuscarALumnosPorNombreCompleto(string frase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BuscarALumnosPorNombreCompleto", ReplyAction="http://tempuri.org/IServicios/BuscarALumnosPorNombreCompletoResponse")]
        System.Threading.Tasks.Task<string> BuscarALumnosPorNombreCompletoAsync(string frase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearCargo", ReplyAction="http://tempuri.org/IServicios/CrearCargoResponse")]
        bool CrearCargo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearCargo", ReplyAction="http://tempuri.org/IServicios/CrearCargoResponse")]
        System.Threading.Tasks.Task<bool> CrearCargoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerCargo", ReplyAction="http://tempuri.org/IServicios/LeerCargoResponse")]
        string LeerCargo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerCargo", ReplyAction="http://tempuri.org/IServicios/LeerCargoResponse")]
        System.Threading.Tasks.Task<string> LeerCargoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarCargo", ReplyAction="http://tempuri.org/IServicios/ActualizarCargoResponse")]
        bool ActualizarCargo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarCargo", ReplyAction="http://tempuri.org/IServicios/ActualizarCargoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCargoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarCargo", ReplyAction="http://tempuri.org/IServicios/EliminarCargoResponse")]
        bool EliminarCargo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarCargo", ReplyAction="http://tempuri.org/IServicios/EliminarCargoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCargoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosCargos", ReplyAction="http://tempuri.org/IServicios/LeerTodosCargosResponse")]
        string LeerTodosCargos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosCargos", ReplyAction="http://tempuri.org/IServicios/LeerTodosCargosResponse")]
        System.Threading.Tasks.Task<string> LeerTodosCargosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearCiudad", ReplyAction="http://tempuri.org/IServicios/CrearCiudadResponse")]
        bool CrearCiudad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearCiudad", ReplyAction="http://tempuri.org/IServicios/CrearCiudadResponse")]
        System.Threading.Tasks.Task<bool> CrearCiudadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerCiudad", ReplyAction="http://tempuri.org/IServicios/LeerCiudadResponse")]
        string LeerCiudad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerCiudad", ReplyAction="http://tempuri.org/IServicios/LeerCiudadResponse")]
        System.Threading.Tasks.Task<string> LeerCiudadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarCiudad", ReplyAction="http://tempuri.org/IServicios/ActualizarCiudadResponse")]
        bool ActualizarCiudad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarCiudad", ReplyAction="http://tempuri.org/IServicios/ActualizarCiudadResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCiudadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarCiudad", ReplyAction="http://tempuri.org/IServicios/EliminarCiudadResponse")]
        bool EliminarCiudad(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarCiudad", ReplyAction="http://tempuri.org/IServicios/EliminarCiudadResponse")]
        System.Threading.Tasks.Task<bool> EliminarCiudadAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasCiudades", ReplyAction="http://tempuri.org/IServicios/LeerTodasCiudadesResponse")]
        string LeerTodasCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasCiudades", ReplyAction="http://tempuri.org/IServicios/LeerTodasCiudadesResponse")]
        System.Threading.Tasks.Task<string> LeerTodasCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearEncargadoCel", ReplyAction="http://tempuri.org/IServicios/CrearEncargadoCelResponse")]
        bool CrearEncargadoCel(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearEncargadoCel", ReplyAction="http://tempuri.org/IServicios/CrearEncargadoCelResponse")]
        System.Threading.Tasks.Task<bool> CrearEncargadoCelAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerEncargadoCel", ReplyAction="http://tempuri.org/IServicios/LeerEncargadoCelResponse")]
        string LeerEncargadoCel(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerEncargadoCel", ReplyAction="http://tempuri.org/IServicios/LeerEncargadoCelResponse")]
        System.Threading.Tasks.Task<string> LeerEncargadoCelAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarEncargadoCel", ReplyAction="http://tempuri.org/IServicios/ActualizarEncargadoCelResponse")]
        bool ActualizarEncargadoCel(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarEncargadoCel", ReplyAction="http://tempuri.org/IServicios/ActualizarEncargadoCelResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEncargadoCelAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarEncargadoCel", ReplyAction="http://tempuri.org/IServicios/EliminarEncargadoCelResponse")]
        bool EliminarEncargadoCel(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarEncargadoCel", ReplyAction="http://tempuri.org/IServicios/EliminarEncargadoCelResponse")]
        System.Threading.Tasks.Task<bool> EliminarEncargadoCelAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosEncargadosCel", ReplyAction="http://tempuri.org/IServicios/LeerTodosEncargadosCelResponse")]
        string LeerTodosEncargadosCel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosEncargadosCel", ReplyAction="http://tempuri.org/IServicios/LeerTodosEncargadosCelResponse")]
        System.Threading.Tasks.Task<string> LeerTodosEncargadosCelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearFamiliaAnfitriona", ReplyAction="http://tempuri.org/IServicios/CrearFamiliaAnfitrionaResponse")]
        bool CrearFamiliaAnfitriona(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearFamiliaAnfitriona", ReplyAction="http://tempuri.org/IServicios/CrearFamiliaAnfitrionaResponse")]
        System.Threading.Tasks.Task<bool> CrearFamiliaAnfitrionaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerFamiliaAnfitriona", ReplyAction="http://tempuri.org/IServicios/LeerFamiliaAnfitrionaResponse")]
        string LeerFamiliaAnfitriona(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerFamiliaAnfitriona", ReplyAction="http://tempuri.org/IServicios/LeerFamiliaAnfitrionaResponse")]
        System.Threading.Tasks.Task<string> LeerFamiliaAnfitrionaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarFamiliaAnfitriona", ReplyAction="http://tempuri.org/IServicios/ActualizarFamiliaAnfitrionaResponse")]
        bool ActualizarFamiliaAnfitriona(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarFamiliaAnfitriona", ReplyAction="http://tempuri.org/IServicios/ActualizarFamiliaAnfitrionaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarFamiliaAnfitrionaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarFamiliaAnfitriona", ReplyAction="http://tempuri.org/IServicios/EliminarFamiliaAnfitrionaResponse")]
        bool EliminarFamiliaAnfitriona(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarFamiliaAnfitriona", ReplyAction="http://tempuri.org/IServicios/EliminarFamiliaAnfitrionaResponse")]
        System.Threading.Tasks.Task<bool> EliminarFamiliaAnfitrionaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasFamiliasAnfitrionas", ReplyAction="http://tempuri.org/IServicios/LeerTodasFamiliasAnfitrionasResponse")]
        string LeerTodasFamiliasAnfitrionas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasFamiliasAnfitrionas", ReplyAction="http://tempuri.org/IServicios/LeerTodasFamiliasAnfitrionasResponse")]
        System.Threading.Tasks.Task<string> LeerTodasFamiliasAnfitrionasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerFamiliaIdentificador", ReplyAction="http://tempuri.org/IServicios/LeerFamiliaIdentificadorResponse")]
        string LeerFamiliaIdentificador(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerFamiliaIdentificador", ReplyAction="http://tempuri.org/IServicios/LeerFamiliaIdentificadorResponse")]
        System.Threading.Tasks.Task<string> LeerFamiliaIdentificadorAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BuscarFamiliaPorNombreCompleto", ReplyAction="http://tempuri.org/IServicios/BuscarFamiliaPorNombreCompletoResponse")]
        string BuscarFamiliaPorNombreCompleto(string nombreApellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/BuscarFamiliaPorNombreCompleto", ReplyAction="http://tempuri.org/IServicios/BuscarFamiliaPorNombreCompletoResponse")]
        System.Threading.Tasks.Task<string> BuscarFamiliaPorNombreCompletoAsync(string nombreApellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearInstitucion", ReplyAction="http://tempuri.org/IServicios/CrearInstitucionResponse")]
        bool CrearInstitucion(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearInstitucion", ReplyAction="http://tempuri.org/IServicios/CrearInstitucionResponse")]
        System.Threading.Tasks.Task<bool> CrearInstitucionAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerInstitucionXML", ReplyAction="http://tempuri.org/IServicios/LeerInstitucionXMLResponse")]
        string LeerInstitucionXML(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerInstitucionXML", ReplyAction="http://tempuri.org/IServicios/LeerInstitucionXMLResponse")]
        System.Threading.Tasks.Task<string> LeerInstitucionXMLAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarInstitucion", ReplyAction="http://tempuri.org/IServicios/ActualizarInstitucionResponse")]
        bool ActualizarInstitucion(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarInstitucion", ReplyAction="http://tempuri.org/IServicios/ActualizarInstitucionResponse")]
        System.Threading.Tasks.Task<bool> ActualizarInstitucionAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarInstitucion", ReplyAction="http://tempuri.org/IServicios/EliminarInstitucionResponse")]
        bool EliminarInstitucion(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarInstitucion", ReplyAction="http://tempuri.org/IServicios/EliminarInstitucionResponse")]
        System.Threading.Tasks.Task<bool> EliminarInstitucionAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasInstituciones", ReplyAction="http://tempuri.org/IServicios/LeerTodasInstitucionesResponse")]
        string LeerTodasInstituciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasInstituciones", ReplyAction="http://tempuri.org/IServicios/LeerTodasInstitucionesResponse")]
        System.Threading.Tasks.Task<string> LeerTodasInstitucionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerInstitucion", ReplyAction="http://tempuri.org/IServicios/LeerInstitucionResponse")]
        string LeerInstitucion(int idInstitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerInstitucion", ReplyAction="http://tempuri.org/IServicios/LeerInstitucionResponse")]
        System.Threading.Tasks.Task<string> LeerInstitucionAsync(int idInstitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosPostulantes", ReplyAction="http://tempuri.org/IServicios/LeerTodosPostulantesResponse")]
        string LeerTodosPostulantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosPostulantes", ReplyAction="http://tempuri.org/IServicios/LeerTodosPostulantesResponse")]
        System.Threading.Tasks.Task<string> LeerTodosPostulantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearIntercambio", ReplyAction="http://tempuri.org/IServicios/CrearIntercambioResponse")]
        bool CrearIntercambio(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearIntercambio", ReplyAction="http://tempuri.org/IServicios/CrearIntercambioResponse")]
        System.Threading.Tasks.Task<bool> CrearIntercambioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerIntercambio", ReplyAction="http://tempuri.org/IServicios/LeerIntercambioResponse")]
        string LeerIntercambio(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerIntercambio", ReplyAction="http://tempuri.org/IServicios/LeerIntercambioResponse")]
        System.Threading.Tasks.Task<string> LeerIntercambioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarIntercambio", ReplyAction="http://tempuri.org/IServicios/ActualizarIntercambioResponse")]
        bool ActualizarIntercambio(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarIntercambio", ReplyAction="http://tempuri.org/IServicios/ActualizarIntercambioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarIntercambioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarIntercambio", ReplyAction="http://tempuri.org/IServicios/EliminarIntercambioResponse")]
        bool EliminarIntercambio(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarIntercambio", ReplyAction="http://tempuri.org/IServicios/EliminarIntercambioResponse")]
        System.Threading.Tasks.Task<bool> EliminarIntercambioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosIntercambios", ReplyAction="http://tempuri.org/IServicios/LeerTodosIntercambiosResponse")]
        string LeerTodosIntercambios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodosIntercambios", ReplyAction="http://tempuri.org/IServicios/LeerTodosIntercambiosResponse")]
        System.Threading.Tasks.Task<string> LeerTodosIntercambiosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerDetallePostulacion", ReplyAction="http://tempuri.org/IServicios/LeerDetallePostulacionResponse")]
        string LeerDetallePostulacion(int idPostulante, string nomPrograma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerDetallePostulacion", ReplyAction="http://tempuri.org/IServicios/LeerDetallePostulacionResponse")]
        System.Threading.Tasks.Task<string> LeerDetallePostulacionAsync(int idPostulante, string nomPrograma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearNota", ReplyAction="http://tempuri.org/IServicios/CrearNotaResponse")]
        bool CrearNota(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearNota", ReplyAction="http://tempuri.org/IServicios/CrearNotaResponse")]
        System.Threading.Tasks.Task<bool> CrearNotaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerNota", ReplyAction="http://tempuri.org/IServicios/LeerNotaResponse")]
        string LeerNota(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerNota", ReplyAction="http://tempuri.org/IServicios/LeerNotaResponse")]
        System.Threading.Tasks.Task<string> LeerNotaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarNota", ReplyAction="http://tempuri.org/IServicios/ActualizarNotaResponse")]
        bool ActualizarNota(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarNota", ReplyAction="http://tempuri.org/IServicios/ActualizarNotaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarNotaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarNota", ReplyAction="http://tempuri.org/IServicios/EliminarNotaResponse")]
        bool EliminarNota(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarNota", ReplyAction="http://tempuri.org/IServicios/EliminarNotaResponse")]
        System.Threading.Tasks.Task<bool> EliminarNotaAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasNotas", ReplyAction="http://tempuri.org/IServicios/LeerTodasNotasResponse")]
        string LeerTodasNotas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerTodasNotas", ReplyAction="http://tempuri.org/IServicios/LeerTodasNotasResponse")]
        System.Threading.Tasks.Task<string> LeerTodasNotasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/NotasAlumno", ReplyAction="http://tempuri.org/IServicios/NotasAlumnoResponse")]
        string NotasAlumno(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/NotasAlumno", ReplyAction="http://tempuri.org/IServicios/NotasAlumnoResponse")]
        System.Threading.Tasks.Task<string> NotasAlumnoAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearPais", ReplyAction="http://tempuri.org/IServicios/CrearPaisResponse")]
        bool CrearPais(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/CrearPais", ReplyAction="http://tempuri.org/IServicios/CrearPaisResponse")]
        System.Threading.Tasks.Task<bool> CrearPaisAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerPais", ReplyAction="http://tempuri.org/IServicios/LeerPaisResponse")]
        string LeerPais(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/LeerPais", ReplyAction="http://tempuri.org/IServicios/LeerPaisResponse")]
        System.Threading.Tasks.Task<string> LeerPaisAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarPais", ReplyAction="http://tempuri.org/IServicios/ActualizarPaisResponse")]
        bool ActualizarPais(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarPais", ReplyAction="http://tempuri.org/IServicios/ActualizarPaisResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPaisAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarPais", ReplyAction="http://tempuri.org/IServicios/EliminarPaisResponse")]
        bool EliminarPais(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarPais", ReplyAction="http://tempuri.org/IServicios/EliminarPaisResponse")]
        System.Threading.Tasks.Task<bool> EliminarPaisAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosChannel : WPF.Portafolio.Servicios.IServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<WPF.Portafolio.Servicios.IServicios>, WPF.Portafolio.Servicios.IServicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LeerTodosPaises() {
            return base.Channel.LeerTodosPaises();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosPaisesAsync() {
            return base.Channel.LeerTodosPaisesAsync();
        }
        
        public bool CrearPrograma(string xml) {
            return base.Channel.CrearPrograma(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearProgramaAsync(string xml) {
            return base.Channel.CrearProgramaAsync(xml);
        }
        
        public string LeerPrograma(string xml) {
            return base.Channel.LeerPrograma(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerProgramaAsync(string xml) {
            return base.Channel.LeerProgramaAsync(xml);
        }
        
        public bool ActualizarPrograma(string xml) {
            return base.Channel.ActualizarPrograma(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProgramaAsync(string xml) {
            return base.Channel.ActualizarProgramaAsync(xml);
        }
        
        public bool EliminarPrograma(string xml) {
            return base.Channel.EliminarPrograma(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProgramaAsync(string xml) {
            return base.Channel.EliminarProgramaAsync(xml);
        }
        
        public string LeerTodosProgramas() {
            return base.Channel.LeerTodosProgramas();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosProgramasAsync() {
            return base.Channel.LeerTodosProgramasAsync();
        }
        
        public bool validarUsuario(string userPass) {
            return base.Channel.validarUsuario(userPass);
        }
        
        public System.Threading.Tasks.Task<bool> validarUsuarioAsync(string userPass) {
            return base.Channel.validarUsuarioAsync(userPass);
        }
        
        public bool CrearUsuario(string xml) {
            return base.Channel.CrearUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string xml) {
            return base.Channel.CrearUsuarioAsync(xml);
        }
        
        public string LeerUsuario(string xml) {
            return base.Channel.LeerUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerUsuarioAsync(string xml) {
            return base.Channel.LeerUsuarioAsync(xml);
        }
        
        public bool ActualizarUsuario(string xml) {
            return base.Channel.ActualizarUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(string xml) {
            return base.Channel.ActualizarUsuarioAsync(xml);
        }
        
        public bool EliminarUsuario(string xml) {
            return base.Channel.EliminarUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string xml) {
            return base.Channel.EliminarUsuarioAsync(xml);
        }
        
        public string LeerTodosUsuarios() {
            return base.Channel.LeerTodosUsuarios();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosUsuariosAsync() {
            return base.Channel.LeerTodosUsuariosAsync();
        }
        
        public string ReadAllVNotasPrograma(int idALumno) {
            return base.Channel.ReadAllVNotasPrograma(idALumno);
        }
        
        public System.Threading.Tasks.Task<string> ReadAllVNotasProgramaAsync(int idALumno) {
            return base.Channel.ReadAllVNotasProgramaAsync(idALumno);
        }
        
        public bool CrearActividad(string xml) {
            return base.Channel.CrearActividad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearActividadAsync(string xml) {
            return base.Channel.CrearActividadAsync(xml);
        }
        
        public string LeerActividad(string xml) {
            return base.Channel.LeerActividad(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerActividadAsync(string xml) {
            return base.Channel.LeerActividadAsync(xml);
        }
        
        public bool ActualizarActividad(string xml) {
            return base.Channel.ActualizarActividad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarActividadAsync(string xml) {
            return base.Channel.ActualizarActividadAsync(xml);
        }
        
        public bool EliminarActividad(string xml) {
            return base.Channel.EliminarActividad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarActividadAsync(string xml) {
            return base.Channel.EliminarActividadAsync(xml);
        }
        
        public string LeerTodasActividades() {
            return base.Channel.LeerTodasActividades();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodasActividadesAsync() {
            return base.Channel.LeerTodasActividadesAsync();
        }
        
        public bool EnlazarPrograma(int idPrograma) {
            return base.Channel.EnlazarPrograma(idPrograma);
        }
        
        public System.Threading.Tasks.Task<bool> EnlazarProgramaAsync(int idPrograma) {
            return base.Channel.EnlazarProgramaAsync(idPrograma);
        }
        
        public bool DesenlazarPrograma() {
            return base.Channel.DesenlazarPrograma();
        }
        
        public System.Threading.Tasks.Task<bool> DesenlazarProgramaAsync() {
            return base.Channel.DesenlazarProgramaAsync();
        }
        
        public bool CrearAdministrativo(string xml) {
            return base.Channel.CrearAdministrativo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearAdministrativoAsync(string xml) {
            return base.Channel.CrearAdministrativoAsync(xml);
        }
        
        public string LeerAdministrativo(string xml) {
            return base.Channel.LeerAdministrativo(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerAdministrativoAsync(string xml) {
            return base.Channel.LeerAdministrativoAsync(xml);
        }
        
        public bool ActualizarAdministrativo(string xml) {
            return base.Channel.ActualizarAdministrativo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAdministrativoAsync(string xml) {
            return base.Channel.ActualizarAdministrativoAsync(xml);
        }
        
        public bool EliminarAdministrativo(string xml) {
            return base.Channel.EliminarAdministrativo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAdministrativoAsync(string xml) {
            return base.Channel.EliminarAdministrativoAsync(xml);
        }
        
        public string LeerTodosAdministrativos() {
            return base.Channel.LeerTodosAdministrativos();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosAdministrativosAsync() {
            return base.Channel.LeerTodosAdministrativosAsync();
        }
        
        public bool CrearAlumno(string xml) {
            return base.Channel.CrearAlumno(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearAlumnoAsync(string xml) {
            return base.Channel.CrearAlumnoAsync(xml);
        }
        
        public string LeerAlumno(string xml) {
            return base.Channel.LeerAlumno(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerAlumnoAsync(string xml) {
            return base.Channel.LeerAlumnoAsync(xml);
        }
        
        public bool ActualizarAlumno(string xml) {
            return base.Channel.ActualizarAlumno(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAlumnoAsync(string xml) {
            return base.Channel.ActualizarAlumnoAsync(xml);
        }
        
        public bool EliminarAlumno(string xml) {
            return base.Channel.EliminarAlumno(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAlumnoAsync(string xml) {
            return base.Channel.EliminarAlumnoAsync(xml);
        }
        
        public string LeerTodosAlumnos() {
            return base.Channel.LeerTodosAlumnos();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosAlumnosAsync() {
            return base.Channel.LeerTodosAlumnosAsync();
        }
        
        public string BuscarALumnosPorNombreCompleto(string frase) {
            return base.Channel.BuscarALumnosPorNombreCompleto(frase);
        }
        
        public System.Threading.Tasks.Task<string> BuscarALumnosPorNombreCompletoAsync(string frase) {
            return base.Channel.BuscarALumnosPorNombreCompletoAsync(frase);
        }
        
        public bool CrearCargo(string xml) {
            return base.Channel.CrearCargo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearCargoAsync(string xml) {
            return base.Channel.CrearCargoAsync(xml);
        }
        
        public string LeerCargo(string xml) {
            return base.Channel.LeerCargo(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerCargoAsync(string xml) {
            return base.Channel.LeerCargoAsync(xml);
        }
        
        public bool ActualizarCargo(string xml) {
            return base.Channel.ActualizarCargo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCargoAsync(string xml) {
            return base.Channel.ActualizarCargoAsync(xml);
        }
        
        public bool EliminarCargo(string xml) {
            return base.Channel.EliminarCargo(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCargoAsync(string xml) {
            return base.Channel.EliminarCargoAsync(xml);
        }
        
        public string LeerTodosCargos() {
            return base.Channel.LeerTodosCargos();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosCargosAsync() {
            return base.Channel.LeerTodosCargosAsync();
        }
        
        public bool CrearCiudad(string xml) {
            return base.Channel.CrearCiudad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearCiudadAsync(string xml) {
            return base.Channel.CrearCiudadAsync(xml);
        }
        
        public string LeerCiudad(string xml) {
            return base.Channel.LeerCiudad(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerCiudadAsync(string xml) {
            return base.Channel.LeerCiudadAsync(xml);
        }
        
        public bool ActualizarCiudad(string xml) {
            return base.Channel.ActualizarCiudad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCiudadAsync(string xml) {
            return base.Channel.ActualizarCiudadAsync(xml);
        }
        
        public bool EliminarCiudad(string xml) {
            return base.Channel.EliminarCiudad(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCiudadAsync(string xml) {
            return base.Channel.EliminarCiudadAsync(xml);
        }
        
        public string LeerTodasCiudades() {
            return base.Channel.LeerTodasCiudades();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodasCiudadesAsync() {
            return base.Channel.LeerTodasCiudadesAsync();
        }
        
        public bool CrearEncargadoCel(string xml) {
            return base.Channel.CrearEncargadoCel(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearEncargadoCelAsync(string xml) {
            return base.Channel.CrearEncargadoCelAsync(xml);
        }
        
        public string LeerEncargadoCel(string xml) {
            return base.Channel.LeerEncargadoCel(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerEncargadoCelAsync(string xml) {
            return base.Channel.LeerEncargadoCelAsync(xml);
        }
        
        public bool ActualizarEncargadoCel(string xml) {
            return base.Channel.ActualizarEncargadoCel(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEncargadoCelAsync(string xml) {
            return base.Channel.ActualizarEncargadoCelAsync(xml);
        }
        
        public bool EliminarEncargadoCel(string xml) {
            return base.Channel.EliminarEncargadoCel(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEncargadoCelAsync(string xml) {
            return base.Channel.EliminarEncargadoCelAsync(xml);
        }
        
        public string LeerTodosEncargadosCel() {
            return base.Channel.LeerTodosEncargadosCel();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosEncargadosCelAsync() {
            return base.Channel.LeerTodosEncargadosCelAsync();
        }
        
        public bool CrearFamiliaAnfitriona(string xml) {
            return base.Channel.CrearFamiliaAnfitriona(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearFamiliaAnfitrionaAsync(string xml) {
            return base.Channel.CrearFamiliaAnfitrionaAsync(xml);
        }
        
        public string LeerFamiliaAnfitriona(string xml) {
            return base.Channel.LeerFamiliaAnfitriona(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerFamiliaAnfitrionaAsync(string xml) {
            return base.Channel.LeerFamiliaAnfitrionaAsync(xml);
        }
        
        public bool ActualizarFamiliaAnfitriona(string xml) {
            return base.Channel.ActualizarFamiliaAnfitriona(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarFamiliaAnfitrionaAsync(string xml) {
            return base.Channel.ActualizarFamiliaAnfitrionaAsync(xml);
        }
        
        public bool EliminarFamiliaAnfitriona(string xml) {
            return base.Channel.EliminarFamiliaAnfitriona(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarFamiliaAnfitrionaAsync(string xml) {
            return base.Channel.EliminarFamiliaAnfitrionaAsync(xml);
        }
        
        public string LeerTodasFamiliasAnfitrionas() {
            return base.Channel.LeerTodasFamiliasAnfitrionas();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodasFamiliasAnfitrionasAsync() {
            return base.Channel.LeerTodasFamiliasAnfitrionasAsync();
        }
        
        public string LeerFamiliaIdentificador(string xml) {
            return base.Channel.LeerFamiliaIdentificador(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerFamiliaIdentificadorAsync(string xml) {
            return base.Channel.LeerFamiliaIdentificadorAsync(xml);
        }
        
        public string BuscarFamiliaPorNombreCompleto(string nombreApellido) {
            return base.Channel.BuscarFamiliaPorNombreCompleto(nombreApellido);
        }
        
        public System.Threading.Tasks.Task<string> BuscarFamiliaPorNombreCompletoAsync(string nombreApellido) {
            return base.Channel.BuscarFamiliaPorNombreCompletoAsync(nombreApellido);
        }
        
        public bool CrearInstitucion(string xml) {
            return base.Channel.CrearInstitucion(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearInstitucionAsync(string xml) {
            return base.Channel.CrearInstitucionAsync(xml);
        }
        
        public string LeerInstitucionXML(string xml) {
            return base.Channel.LeerInstitucionXML(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerInstitucionXMLAsync(string xml) {
            return base.Channel.LeerInstitucionXMLAsync(xml);
        }
        
        public bool ActualizarInstitucion(string xml) {
            return base.Channel.ActualizarInstitucion(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarInstitucionAsync(string xml) {
            return base.Channel.ActualizarInstitucionAsync(xml);
        }
        
        public bool EliminarInstitucion(string xml) {
            return base.Channel.EliminarInstitucion(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarInstitucionAsync(string xml) {
            return base.Channel.EliminarInstitucionAsync(xml);
        }
        
        public string LeerTodasInstituciones() {
            return base.Channel.LeerTodasInstituciones();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodasInstitucionesAsync() {
            return base.Channel.LeerTodasInstitucionesAsync();
        }
        
        public string LeerInstitucion(int idInstitucion) {
            return base.Channel.LeerInstitucion(idInstitucion);
        }
        
        public System.Threading.Tasks.Task<string> LeerInstitucionAsync(int idInstitucion) {
            return base.Channel.LeerInstitucionAsync(idInstitucion);
        }
        
        public string LeerTodosPostulantes() {
            return base.Channel.LeerTodosPostulantes();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosPostulantesAsync() {
            return base.Channel.LeerTodosPostulantesAsync();
        }
        
        public bool CrearIntercambio(string xml) {
            return base.Channel.CrearIntercambio(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearIntercambioAsync(string xml) {
            return base.Channel.CrearIntercambioAsync(xml);
        }
        
        public string LeerIntercambio(string xml) {
            return base.Channel.LeerIntercambio(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerIntercambioAsync(string xml) {
            return base.Channel.LeerIntercambioAsync(xml);
        }
        
        public bool ActualizarIntercambio(string xml) {
            return base.Channel.ActualizarIntercambio(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarIntercambioAsync(string xml) {
            return base.Channel.ActualizarIntercambioAsync(xml);
        }
        
        public bool EliminarIntercambio(string xml) {
            return base.Channel.EliminarIntercambio(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarIntercambioAsync(string xml) {
            return base.Channel.EliminarIntercambioAsync(xml);
        }
        
        public string LeerTodosIntercambios() {
            return base.Channel.LeerTodosIntercambios();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodosIntercambiosAsync() {
            return base.Channel.LeerTodosIntercambiosAsync();
        }
        
        public string LeerDetallePostulacion(int idPostulante, string nomPrograma) {
            return base.Channel.LeerDetallePostulacion(idPostulante, nomPrograma);
        }
        
        public System.Threading.Tasks.Task<string> LeerDetallePostulacionAsync(int idPostulante, string nomPrograma) {
            return base.Channel.LeerDetallePostulacionAsync(idPostulante, nomPrograma);
        }
        
        public bool CrearNota(string xml) {
            return base.Channel.CrearNota(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearNotaAsync(string xml) {
            return base.Channel.CrearNotaAsync(xml);
        }
        
        public string LeerNota(string xml) {
            return base.Channel.LeerNota(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerNotaAsync(string xml) {
            return base.Channel.LeerNotaAsync(xml);
        }
        
        public bool ActualizarNota(string xml) {
            return base.Channel.ActualizarNota(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarNotaAsync(string xml) {
            return base.Channel.ActualizarNotaAsync(xml);
        }
        
        public bool EliminarNota(string xml) {
            return base.Channel.EliminarNota(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarNotaAsync(string xml) {
            return base.Channel.EliminarNotaAsync(xml);
        }
        
        public string LeerTodasNotas() {
            return base.Channel.LeerTodasNotas();
        }
        
        public System.Threading.Tasks.Task<string> LeerTodasNotasAsync() {
            return base.Channel.LeerTodasNotasAsync();
        }
        
        public string NotasAlumno(string xml) {
            return base.Channel.NotasAlumno(xml);
        }
        
        public System.Threading.Tasks.Task<string> NotasAlumnoAsync(string xml) {
            return base.Channel.NotasAlumnoAsync(xml);
        }
        
        public bool CrearPais(string xml) {
            return base.Channel.CrearPais(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearPaisAsync(string xml) {
            return base.Channel.CrearPaisAsync(xml);
        }
        
        public string LeerPais(string xml) {
            return base.Channel.LeerPais(xml);
        }
        
        public System.Threading.Tasks.Task<string> LeerPaisAsync(string xml) {
            return base.Channel.LeerPaisAsync(xml);
        }
        
        public bool ActualizarPais(string xml) {
            return base.Channel.ActualizarPais(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPaisAsync(string xml) {
            return base.Channel.ActualizarPaisAsync(xml);
        }
        
        public bool EliminarPais(string xml) {
            return base.Channel.EliminarPais(xml);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPaisAsync(string xml) {
            return base.Channel.EliminarPaisAsync(xml);
        }
    }
}
